# --------------------------------------------
# binning section use by the 'bin' command
# --------------------------------------------
binning:

  # metrics: WHAT should be binned?
  metrics:
  - name: obs
    source: "@ObsValue"

  # bins: HOW should it be binned?
  bins:
  - name: latlon
    dimensions:
    - name: latitude
      resolution: 1.0
    - name: longitude
      resolution: 1.0
#
  - name: global
    dimensions: []

  variables: [brightness_temperature_1, 
              brightness_temperature_12]   
# -------------------------------------------
# plotting section used by the 'plot' command
# -------------------------------------------
plotting:

  # WHAT should be plotted?
  basic:
  - class: PlotType2D*
    variables: [brightness_temperature_12] 
    metric: [obs, hofx, ombg]
    stat: [count]

