# --------------------------------------------
# binning section use by the 'bin' command
# --------------------------------------------
binning:

  # metrics: WHAT should be binned?
  metrics:
  - name: obs
    source: "@ObsValue"
  - name: hofx
    source: "@hofx"
  - name: ombg
    source: "@ObsValue - @hofx"

  # bins: HOW should it be binned?
  bins:
  - name: latlon
    dimensions:
    - name: latitude
      resolution: 1.0
    - name: longitude
      resolution: 1.0
#
  - name: global
    dimensions: []

# -------------------------------------------
# plotting section used by the 'plot' command
# -------------------------------------------
plotting:

  # WHAT should be plotted?
  basic:
  - class: PlotType2D*
    metric: [obs]
    stat: [count]

