# --------------------------------------------
# binning section use by the 'bin' command
# --------------------------------------------
binning:

  # metrics: WHAT should be binned?
  metrics:
  - name: obs
    source: "@ObsValue"
  - name: hofx
    source: "@hofx"
  - name: ombg
    source: "@ObsValue - @hofx"

  # bins: HOW should it be binned?
  bins:
  - name: latlon
    dimensions:
    - name: latitude
      resolution: 1.0
    - name: longitude
      resolution: 1.0
#
  - name: global
    dimensions: []

  variables: [brightness_temperature_19]   
# -------------------------------------------
# plotting section used by the 'plot' command
# -------------------------------------------
plotting:

  # WHAT should be plotted?
  basic:
  - class: PlotType2D*
    variables: [brightness_temperature_19]
    metric: [obs, hofx, ombg]
    stat: [mean, stddev, count]

  # composite: #TODO, currently in progress
  # - class: PlotType1D*
  #   name: rmsd
  #   plot:
  #   - metric: ombg
  #     stat: rmsd
  #     args: {ls: '-'}
  #   - metric: oman
  #     stat: rmsd
  #     args: {ls: '--'}

  # TODO currently in progress
  # args: # fine tune the plotting
  # ##-------------------------------------------------
  # ## Format is one or more copies of the following
  # ##-------------------------------------------------
  # # - match:
  # #     variable:
  # #     binning:
  # #     class:
  # #     stat:
  # #     metric:
  # #     custom: ?
  # #   args:

  # - match: {stat: rmsd}
  #   args: {cmap: inferno}

  # - match: {class: PlotType2DLatLon}
  #   args:
  #     projection: Orthographic
  #     projection_args:
  #       central_longitude: 0.0
  #       central_latitude: 90.0
