# --------------------------------------------
# binning section use by the 'bin' command
# --------------------------------------------
binning:

  # metrics: WHAT should be binned?
  metrics:
  - name: obs
    source: "@ObsValue"
  - name: hofx
    source: "@hofx"
  - name: ombg
    source: "@ObsValue - @hofx"

  # bins: HOW should it be binned?
  bins:
  - name: profile
    dimensions:
    - name: air_pressure
      resolution: 5000
      bounds: [0, 100000]

  - name: global
    dimensions: []

# -------------------------------------------
# plotting section used by the 'plot' command
# -------------------------------------------
plotting:

  # WHAT should be plotted?
  basic:
  - class: PlotType1D*
    metric: [obs]
    stat: [count]

