# --------------------------------------------
# binning section use by the 'bin' command
# --------------------------------------------
binning:

  # metrics: WHAT should be binned?
  metrics:
  - name: obs
    source: "@ObsValue"
  - name: hofx
    source: "@hofx"
  - name: ombg
    source: "@ObsValue - @hofx"
  - name: hofxDiff
    source: "@hofx - @GsiHofX"  
#  - name: oman
#    source: "@oman"  
#  - name: inc
#    source: "@oman - @ombg"

  # bins: HOW should it be binned?
  bins:
  - name: profile
    dimensions:
    - name: air_pressure
      resolution: 5000
      bounds: [0, 100000]
#
#  - name: global
#    dimensions: []

  # - name: nino34
  #   dimensions:
  #   - name: latitude
  #     bounds: [-5.0, 5.0]
  #   - name: longitude
  #     bounds: [-170.0, -120.0]


# -------------------------------------------
# plotting section used by the 'plot' command
# -------------------------------------------
plotting:

  # WHAT should be plotted?
  basic:
  - class: PlotType1D*
    metric: [obs, hofx, ombg, hofxDiff]
    stat: [mean, stddev, count]

  # composite: #TODO, currently in progress
  # - class: PlotType1D*
  #   name: rmsd
  #   plot:
  #   - metric: ombg
  #     stat: rmsd
  #     args: {ls: '-'}
  #   - metric: oman
  #     stat: rmsd
  #     args: {ls: '--'}

  # TODO currently in progress
  # args: # fine tune the plotting
  # ##-------------------------------------------------
  # ## Format is one or more copies of the following
  # ##-------------------------------------------------
  # # - match:
  # #     variable:
  # #     binning:
  # #     class:
  # #     stat:
  # #     metric:
  # #     custom: ?
  # #   args:

  # - match: {stat: rmsd}
  #   args: {cmap: inferno}

  # - match: {class: PlotType2DLatLon}
  #   args:
  #     projection: Orthographic
  #     projection_args:
  #       central_longitude: 0.0
  #       central_latitude: 90.0