cost function:

  # Cost function setup
  cost type: 3D-Var
  window begin: '2018-04-14T21:00:00Z'
  window length: PT6H
  analysis variables: &anvars [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]

  # Background Geometry
  geometry:
    nml_file_mpp: /opt/jedi/build/fv3-jedi/test/Data/fv3files/fmsmpp.nml
    trc_file: /opt/jedi/build/fv3-jedi/test/Data/fv3files/field_table
    akbk: /opt/jedi/build/fv3-jedi/test/Data/fv3files/akbk64.nc4
    # input.nml
    layout: [1,1]
    io_layout: [1,1]
    npx: 13
    npy: 13
    npz: 64
    ntiles: 6
    fieldsets:
    - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/dynamics.yaml
    - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/ufo.yaml

  # Background
  background:
    filetype: gfs
    datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/bkg
    filename_core: 20180415.000000.fv_core.res.nc
    filename_trcr: 20180415.000000.fv_tracer.res.nc
    filename_sfcd: 20180415.000000.sfc_data.nc
    filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
    filename_cplr: 20180415.000000.coupler.res
    state variables: [ua,va,T,DELP,ps,sphum,ice_wat,liq_wat,o3mr,phis,
                      slmsk,sheleg,tsea,vtype,stype,vfrac,stc,smc,snwdph,
                      u_srf,v_srf,f10m]

  # Background error covariance
  background error:

    covariance model: ensemble

    # Datetime of cov model
    date: '2018-04-15T00:00:00Z'

    # Localization operator
    localization:
      timeslots: ['2018-04-15T00:00:00Z']
      localization method: BUMP
      localization variables: *anvars
      bump:
        prefix: bump/fv3jedi_bumpparameters_nicas_gfs
        method: loc
        strategy: common
        load_nicas: 1
        mpicom: 2
        verbosity: main
        io_keys: ["common"]
        io_values: ["fixed_2500km_0.3"]

    members:
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem001/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem002/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem003/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem004/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem005/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem006/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem007/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem008/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem009/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
    - filetype: gfs
      state variables: *anvars
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem010/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res

  # Observation operators
  # ---------------------
  observations:
  - obs space:
      name: Aircraft
      obsdatain:
        obsfile: /opt/jedi/build/fv3-jedi/test/Data/obs/testinput_tier_1/aircraft_obs_2018041500_m.nc4
      obsdataout:
        obsfile: run-3denvar/hofx/aircraft_hyb-3dvar-gfs_2018041500_m.nc4
      simulated variables: [eastward_wind, northward_wind, air_temperature]
    obs operator:
      name: VertInterp
    obs error:
      covariance model: diagonal
    obs filters:
    - filter: PreQC
      maxvalue: 3
    - filter: Background Check
      filter variables:
      - name: eastward_wind
      - name: northward_wind
      - name: air_temperature
      threshold: 6.0
  - obs space:
      name: AMSUA-NOAA19
      obsdatain:
        obsfile: /opt/jedi/build/fv3-jedi/test/Data/obs/testinput_tier_1/amsua_n19_obs_2018041500_m.nc4
      simulated variables: [brightness_temperature]
      channels: 1-15
    obs operator:
      name: CRTM
      Absorbers: [H2O,O3]
      obs options:
        Sensor_ID: amsua_n19
        EndianType: little_endian
        CoefficientPath: /opt/jedi/build/fv3-jedi/test/Data/crtm/
    obs error:
      covariance model: diagonal
    obs filters:
    - filter: Bounds Check
      filter variables:
      - name: brightness_temperature
        channels: 1-15
      minvalue: 100.0
      maxvalue: 500.0
    - filter: Background Check
      filter variables:
      - name: brightness_temperature
        channels: 1-15
      threshold: 3.0
  - obs space:
      name: SfcObs
      obsdatain:
        obsfile: /opt/jedi/build/fv3-jedi/test/Data/obs/testinput_tier_1/sfc_obs_2018041500_m.nc4
      simulated variables: [surface_pressure]
    obs operator:
      name: SfcPCorrected
      da_psfc_scheme: UKMO
    linear obs operator:
      name: Identity
    obs error:
      covariance model: diagonal
    obs filters:
    - filter: Background Check
      threshold: 1000

# Variational data assimilation configuration
# -------------------------------------------
variational:

  # Minimizer
  minimizer:
    algorithm: DRIPCG

  # Outer loops
  iterations:
  - ninner: 10
    gradient norm reduction: 1e-10
    test: on
    geometry:
      trc_file: /opt/jedi/build/fv3-jedi/test/Data/fv3files/field_table
      akbk: /opt/jedi/build/fv3-jedi/test/Data/fv3files/akbk64.nc4
      # input.nml
      layout: [1,1]
      io_layout: [1,1]
      npx: 13
      npy: 13
      npz: 64
      ntiles: 6
      fieldsets:
      - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/dynamics.yaml
      - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/ufo.yaml
    diagnostics:
      departures: ombg

# Final diagnostics
final:
  diagnostics:
    departures: oman

# Analysis output
output:
  filetype: gfs
  datapath: run-3denvar/analysis/
  filename_core: 3denvar.fv_core.res.nc
  filename_trcr: 3denvar.fv_tracer.res.nc
  filename_sfcd: 3denvar.sfc_data.nc
  filename_sfcw: 3denvar.fv_srf_wnd.res.nc
  filename_cplr: 3denvar.coupler.res
  first: PT0H
  frequency: PT1H
