state geometry:
  nml_file_mpp: /opt/jedi/build/fv3-jedi/test/Data/fv3files/fmsmpp.nml
  trc_file: /opt/jedi/build/fv3-jedi/test/Data/fv3files/field_table
  akbk: /opt/jedi/build/fv3-jedi/test/Data/fv3files/akbk64.nc4
  # input.nml
  layout: [1,1]
  io_layout: [1,1]
  npx: 13
  npy: 13
  npz: 64
  ntiles: 6
  fieldsets:
    - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/dynamics.yaml
increment geometry:
  trc_file: /opt/jedi/build/fv3-jedi/test/Data/fv3files/field_table
  akbk: /opt/jedi/build/fv3-jedi/test/Data/fv3files/akbk64.nc4
  # input.nml
  layout: [1,1]
  io_layout: [1,1]
  npx: 25
  npy: 25
  npz: 64
  ntiles: 6
  fieldsets:
    - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/dynamics.yaml
state1: #Analysis
  filetype: gfs
  datapath: run-3denvar/analysis
  filename_core: 20180415.000000.3denvar.fv_core.res.nc
  filename_trcr: 20180415.000000.3denvar.fv_tracer.res.nc
  filename_sfcd: 20180415.000000.3denvar.sfc_data.nc
  filename_sfcw: 20180415.000000.3denvar.fv_srf_wnd.res.nc
  filename_cplr: 20180415.000000.3denvar.coupler.res
  psinfile: true
  state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
state2: #background
  filetype: gfs
  datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/bkg/
  filename_core: 20180415.000000.fv_core.res.nc
  filename_trcr: 20180415.000000.fv_tracer.res.nc
  filename_sfcd: 20180415.000000.sfc_data.nc
  filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
  filename_cplr: 20180415.000000.coupler.res
  state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
output:
  filetype: latlon
  filename: run-3denvar/increment/3denvar.latlon.
