cost function:
  cost type: 4D-Ens-Var
  analysis variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
  window begin: '2018-04-14T21:00:00Z'
  window length: PT6H
  subwindow: PT3H
  background:
    states:
    - filetype: gfs
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/bkg/
      filename_core: 20180414.210000.fv_core.res.nc
      filename_trcr: 20180414.210000.fv_tracer.res.nc
      filename_sfcd: 20180414.210000.sfc_data.nc
      filename_sfcw: 20180414.210000.fv_srf_wnd.res.nc
      filename_cplr: 20180414.210000.coupler.res
      state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr,phis,
                        slmsk,sheleg,tsea,vtype,stype,vfrac,stc,smc,snwdph,
                        u_srf,v_srf,f10m]
    - filetype: gfs
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/bkg/
      filename_core: 20180415.000000.fv_core.res.nc
      filename_trcr: 20180415.000000.fv_tracer.res.nc
      filename_sfcd: 20180415.000000.sfc_data.nc
      filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.000000.coupler.res
      state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr,phis,
                        slmsk,sheleg,tsea,vtype,stype,vfrac,stc,smc,snwdph,
                        u_srf,v_srf,f10m]
    - filetype: gfs
      datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/bkg/
      filename_core: 20180415.030000.fv_core.res.nc
      filename_trcr: 20180415.030000.fv_tracer.res.nc
      filename_sfcd: 20180415.030000.sfc_data.nc
      filename_sfcw: 20180415.030000.fv_srf_wnd.res.nc
      filename_cplr: 20180415.030000.coupler.res
      state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr,phis,
                        slmsk,sheleg,tsea,vtype,stype,vfrac,stc,smc,snwdph,
                        u_srf,v_srf,f10m]
  background error:
    covariance model: ensemble
    ensemble:
    localization:
      bump:
        prefix: bump/fv3jedi_bumpparameters_nicas_gfs
        method: loc
        strategy: common
        load_nicas: 1
        mpicom: 2
        verbosity: main
        io_keys: ["common"]
        io_values: ["fixed_2500km_0.3"]
      localization method: BUMP
      timeslots: ['2018-04-14T21:00:00Z','2018-04-15T00:00:00Z','2018-04-15T03:00:00Z']
      localization variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
    members:
    - states:
      - filetype: gfs
        state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
        datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem001/
        filename_core: 20180414.210000.fv_core.res.nc
        filename_trcr: 20180414.210000.fv_tracer.res.nc
        filename_sfcd: 20180414.210000.sfc_data.nc
        filename_sfcw: 20180414.210000.fv_srf_wnd.res.nc
        filename_cplr: 20180414.210000.coupler.res
      - filetype: gfs
        state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
        datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem001/
        filename_core: 20180415.000000.fv_core.res.nc
        filename_trcr: 20180415.000000.fv_tracer.res.nc
        filename_sfcd: 20180415.000000.sfc_data.nc
        filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
        filename_cplr: 20180415.000000.coupler.res
      - filetype: gfs
        state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
        datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem001/
        filename_core: 20180415.030000.fv_core.res.nc
        filename_trcr: 20180415.030000.fv_tracer.res.nc
        filename_sfcd: 20180415.030000.sfc_data.nc
        filename_sfcw: 20180415.030000.fv_srf_wnd.res.nc
        filename_cplr: 20180415.030000.coupler.res
    - states:
      - filetype: gfs
        state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
        datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem002/
        filename_core: 20180414.210000.fv_core.res.nc
        filename_trcr: 20180414.210000.fv_tracer.res.nc
        filename_sfcd: 20180414.210000.sfc_data.nc
        filename_sfcw: 20180414.210000.fv_srf_wnd.res.nc
        filename_cplr: 20180414.210000.coupler.res
      - filetype: gfs
        state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
        datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem002/
        filename_core: 20180415.000000.fv_core.res.nc
        filename_trcr: 20180415.000000.fv_tracer.res.nc
        filename_sfcd: 20180415.000000.sfc_data.nc
        filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
        filename_cplr: 20180415.000000.coupler.res
      - filetype: gfs
        state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
        datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem002/
        filename_core: 20180415.030000.fv_core.res.nc
        filename_trcr: 20180415.030000.fv_tracer.res.nc
        filename_sfcd: 20180415.030000.sfc_data.nc
        filename_sfcw: 20180415.030000.fv_srf_wnd.res.nc
        filename_cplr: 20180415.030000.coupler.res
    - states:
      - filetype: gfs
        state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
        datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem003/
        filename_core: 20180414.210000.fv_core.res.nc
        filename_trcr: 20180414.210000.fv_tracer.res.nc
        filename_sfcd: 20180414.210000.sfc_data.nc
        filename_sfcw: 20180414.210000.fv_srf_wnd.res.nc
        filename_cplr: 20180414.210000.coupler.res
      - filetype: gfs
        state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
        datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem003/
        filename_core: 20180415.000000.fv_core.res.nc
        filename_trcr: 20180415.000000.fv_tracer.res.nc
        filename_sfcd: 20180415.000000.sfc_data.nc
        filename_sfcw: 20180415.000000.fv_srf_wnd.res.nc
        filename_cplr: 20180415.000000.coupler.res
      - filetype: gfs
        state variables: [ua,va,T,ps,sphum,ice_wat,liq_wat,o3mr]
        datapath: /opt/jedi/build/fv3-jedi/test/Data/inputs/gfs_c12/mem003/
        filename_core: 20180415.030000.fv_core.res.nc
        filename_trcr: 20180415.030000.fv_tracer.res.nc
        filename_sfcd: 20180415.030000.sfc_data.nc
        filename_sfcw: 20180415.030000.fv_srf_wnd.res.nc
        filename_cplr: 20180415.030000.coupler.res
  observations:
  - obs space:
      name: Aircraft
      obsdatain:
        obsfile: /opt/jedi/build/fv3-jedi/test/Data/obs/testinput_tier_1/aircraft_obs_2018041500_m.nc4
      # obsdataout:
        # obsfile: /opt/jedi/build/fv3-jedi/test/Data/hofx/aircraft_4denvar-gfs_2018041500_m.nc4
      simulated variables: [eastward_wind, northward_wind, air_temperature]
    obs operator:
      name: VertInterp
    obs error:
      covariance model: diagonal
    obs filters:
    - filter: PreQC
      maxvalue: 3
    - filter: Background Check
      filter variables:
      - name: eastward_wind
      - name: northward_wind
      - name: air_temperature
      threshold: 6.0
  geometry:
    nml_file_mpp: /opt/jedi/build/fv3-jedi/test/Data/fv3files/fmsmpp.nml
    trc_file: /opt/jedi/build/fv3-jedi/test/Data/fv3files/field_table
    akbk: /opt/jedi/build/fv3-jedi/test/Data/fv3files/akbk64.nc4
    # input.nml
    layout: [1,1]
    io_layout: [1,1]
    npx: 13
    npy: 13
    npz: 64
    ntiles: 6
    fieldsets:
      - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/dynamics.yaml
      - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/ufo.yaml
output:
  filetype: gfs
  datapath: run-4denvar/analysis/
  filename_core: 4denvar-gfs.fv_core.res.nc
  filename_trcr: 4denvar-gfs.fv_tracer.res.nc
  filename_sfcd: 4denvar-gfs.sfc_data.nc
  filename_sfcw: 4denvar-gfs.fv_srf_wnd.res.nc
  filename_cplr: 4denvar-gfs.coupler.res
  first: PT0H
  frequency: PT3H
final:
  diagnostics:
    departures: oma
variational:
  minimizer:
    algorithm: DRIPCG
  iterations:
  - ninner: 2
    gradient norm reduction: 1e-10
    test: on
    geometry:
      trc_file: /opt/jedi/build/fv3-jedi/test/Data/fv3files/field_table
      akbk: /opt/jedi/build/fv3-jedi/test/Data/fv3files/akbk64.nc4
      # input.nml
      layout: [1,1]
      io_layout: [1,1]
      npx: 13
      npy: 13
      npz: 64
      ntiles: 6
      fieldsets:
      - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/dynamics.yaml
      - fieldset: /opt/jedi/build/fv3-jedi/test/Data/fieldsets/ufo.yaml
    diagnostics:
      departures: ombg
