state geometry:
  nml_file_mpp: Data/fv3files/fmsmpp.nml
  trc_file: Data/fv3files/field_table
  akbk: Data/fv3files/akbk64.nc4
  # input.nml
  layout: [1,1]
  io_layout: [1,1]
  npx: 25
  npy: 25
  npz: 64
  ntiles: 6
  fieldsets:
    - fieldset: Data/fieldsets/dynamics.yaml
increment geometry:
  trc_file: Data/fv3files/field_table
  akbk: Data/fv3files/akbk64.nc4
  # input.nml
  layout: [1,1]
  io_layout: [1,1]
  npx: 25
  npy: 25
  npz: 64
  ntiles: 6
  fieldsets:
    - fieldset: Data/fieldsets/dynamics.yaml
state1: #Analysis
  filetype: gfs
  datapath: Data/analysis
  filename_core: 20180415.000000.hyb-3dvar.c24.fv_core.res.nc
  filename_trcr: 20180415.000000.hyb-3dvar.c24.fv_tracer.res.nc
  filename_sfcd: 20180415.000000.hyb-3dvar.c24.sfc_data.nc
  filename_sfcw: 20180415.000000.hyb-3dvar.c24.fv_srf_wnd.res.nc
  filename_cplr: 20180415.000000.hyb-3dvar.c24.coupler.res
  state variables: [ua,va,T,DELP,sphum,ice_wat,liq_wat,o3mr]
state2: #background
  filetype: gfs
  datapath: Data/
  filename_core: 20180415.000000.c24.fv_core.res.nc
  filename_trcr: 20180415.000000.c24.fv_tracer.res.nc
  filename_sfcd: 20180415.000000.c24.sfc_data.nc
  filename_sfcw: 20180415.000000.c24.fv_srf_wnd.res.nc
  filename_cplr: 20180415.000000.c24.coupler.res
  state variables: [ua,va,T,DELP,sphum,ice_wat,liq_wat,o3mr]
output:
  filetype: gfs
  datapath: Data/increment/
  filename_core: hyb-3dvar-gfs.c24.fv_core.res.nc
  filename_trcr: hyb-3dvar-gfs.c24.fv_tracer.res.nc
  filename_sfcd: hyb-3dvar-gfs.c24.sfc_data.nc
  filename_sfcw: hyb-3dvar-gfs.c24.fv_srf_wnd.res.nc
  filename_cplr: hyb-3dvar-gfs.c24.coupler.res
