#
# (C) Copyright 2020 UCAR
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#

Geometry: fv3

Fields:
  - FieldIONames: [u, ud, U]
    FieldName: ud
    LongName: u_component_of_native_D_grid_wind
    Units: ms-1
    Space: vector
    StaggerLoc: northsouth
    IOFile: core

  - FieldIONames: [v, vd, V]
    FieldName: vd
    LongName: v_component_of_native_D_grid_wind
    Units: ms-1
    Space: vector
    StaggerLoc: eastwest
    IOFile: core

  - FieldIONames: [uc]
    FieldName: uc
    LongName: u_component_of_native_C_grid_wind
    Units: ms-1
    Space: vector
    StaggerLoc: eastwest

  - FieldIONames: [vc]
    FieldName: vc
    LongName: v_component_of_native_C_grid_wind
    Units: ms-1
    Space: vector
    StaggerLoc: northsouth

  - FieldIONames: [ua, eastward_wind]
    FieldName: ua
    LongName: eastward_wind
    Units: ms-1
    IOFile: core

  - FieldIONames: [va, northward_wind]
    FieldName: va
    LongName: northward_wind
    Units: ms-1
    IOFile: core

  - FieldIONames: [t, T, air_temperature, temperature]
    FieldName: t
    LongName: air_temperature
    Units: K
    IOFile: core

  - FieldIONames: [tv, Tv, virtual_temperature]
    FieldName: tv
    LongName: virtual_temperature
    Units: K
    IOFile: core

  - FieldIONames: [pt, PT]
    FieldName: pt
    LongName: potential_temperature
    Units: K
    IOFile: core

  - FieldIONames: [delp, DELP, air_pressure_thickness]
    FieldName: delp
    LongName: air_pressure_thickness
    Units: pa
    IOFile: core

  - FieldIONames: [pkz, PKZ]
    FieldName: pkz
    LongName: air_pressure_to_kappa
    Units: Pa
    IOFile: core

  - FieldIONames: [pe, PE, air_pressure_levels]
    FieldName: pe
    LongName: air_pressure_levels
    Units: Pa
    Levels: half
    IOFile: core

  - FieldIONames: [p, P, air_pressure]
    FieldName: p
    LongName: air_pressure
    Units: Pa
    Levels: full
    IOFile: core

  - FieldIONames: [ps, surface_pressure]
    FieldName: ps
    LongName: surface_pressure
    Units: Pa
    Levels: 1
    IOFile: core

  - FieldIONames: [q, sphum, Q, specific_humidity]
    FieldName: sphum
    LongName: specific_humidity
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [rh, RH, relative_humidity]
    FieldName: rh
    LongName: relative_humidity
    Units: 1
    IOFile: tracer

  - FieldIONames: [qi, ice_wat]
    FieldName: ice_wat
    LongName: cloud_liquid_ice
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [ql, liq_wat]
    FieldName: liq_wat
    LongName: cloud_liquid_water
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [qils, QILS]
    FieldName: qils
    LongName: mass_fraction_of_large_scale_cloud_ice_water
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [qicn, QICN]
    FieldName: qicn
    LongName: mass_fraction_of_convective_cloud_ice_water
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [qlls, QLLS]
    FieldName: qlls
    LongName: mass_fraction_of_large_scale_cloud_liquid_water
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [qlcn, QLCN]
    FieldName: qlcn
    LongName: mass_fraction_of_convective_cloud_liquid_water
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [qicnf, QICNF]
    FieldName: qicnf
    LongName: fraction_of_large_scale_cloud_ice_water_in_total
    Units: 1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [qlcnf, QLCNF]
    FieldName: qlcnf
    LongName: fraction_of_large_scale_cloud_liquid_water_in_total
    Units: 1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [qs, snowwat]
    FieldName: snowwat
    LongName: snow_water
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [qr, rainwat]
    FieldName: rainwat
    LongName: rain_water
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [graupel]
    FieldName: graupel
    LongName: graupel
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [cld_amt]
    FieldName: cld_amt
    LongName: cld_amt
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [o3, o3mr]
    FieldName: o3mr
    LongName: ozone_mass_mixing_ratio
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [ox, OX]
    FieldName: ox
    LongName: odd_oxygen_mixing_ratio
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [w, W]
    FieldName: w
    LongName: upward_air_velocity
    Units: ms-1
    IOFile: core

  - FieldIONames: [delz, DZ]
    FieldName: delz
    LongName: layer_thickness
    Units: m
    IOFile: core

  - FieldIONames: [phis]
    FieldName: phis
    LongName: surface_geopotential_height
    Units: m
    Levels: 1
    IOFile: core

  - FieldIONames: [psi]
    FieldName: psi
    LongName: stream_function
    Units: m+2s
    IOFile: core

  - FieldIONames: [chi]
    FieldName: chi
    LongName: velocity_potential
    Units: m+2s
    IOFile: core

  - FieldIONames: [vort]
    FieldName: vort
    LongName: vorticity
    Units: m+2s
    IOFile: core

  - FieldIONames: [divg]
    FieldName: divg
    LongName: divergence
    Units: m+2s
    IOFile: core

  - FieldIONames: [slmsk]
    FieldName: slmsk
    LongName: slmsk
    Units: none
    Levels: 1
    IOFile: surface

  - FieldIONames: [sheleg]
    FieldName: sheleg
    LongName: sheleg
    Units: none
    Levels: 1
    IOFile: surface

  - FieldIONames: [tsea, ts, sea_surface_temperature]
    FieldName: tsea
    LongName: sea_surface_temperature
    Units: K
    Levels: 1
    IOFile: surface

  - FieldIONames: [vtype]
    FieldName: vtype
    LongName: vtype
    Units: none
    Levels: 1
    Kind: integer
    IOFile: surface

  - FieldIONames: [stype]
    FieldName: stype
    LongName: stype
    Units: none
    Levels: 1
    Kind: integer
    IOFile: surface

  - FieldIONames: [vfrac]
    FieldName: vfrac
    LongName: vfrac
    Units: none
    Levels: 1
    IOFile: surface

  - FieldIONames: [stc]
    FieldName: stc
    LongName: stc
    Units: none
    Levels: 4
    IOFile: surface

  - FieldIONames: [soilt]
    FieldName: stc
    LongName: soilt
    Units: none
    Levels: 1
    IOFile: surface

  - FieldIONames: [smc]
    FieldName: smc
    LongName: smc
    Units: none
    Levels: 4
    IOFile: surface

  - FieldIONames: [soilm]
    FieldName: smc
    LongName: soilm
    Units: none
    Levels: 1
    IOFile: surface

  - FieldIONames: [snwdph]
    FieldName: snwdph
    LongName: snwdph
    Units: none
    Levels: 1
    IOFile: surface

  - FieldIONames: [u_srf, u10m]
    FieldName: u_srf
    LongName: u_srf
    Units: ms-1
    Levels: 1
    IOFile: surface_wind

  - FieldIONames: [v_srf, v10m]
    FieldName: v_srf
    LongName: v_srf
    Units: ms-1
    Levels: 1
    IOFile: surface_wind

  - FieldIONames: [f10m]
    FieldName: f10m
    LongName: f10m
    Units: none
    Levels: 1
    IOFile: surface

  - FieldIONames: [sss, sea_surface_salinity]
    FieldName: sss
    LongName: sea_surface_salinity
    Units: none
    Levels: 1
    IOFile: surface

  - FieldIONames: [qls]
    FieldName: qls
    LongName: initial_mass_fraction_of_large_scale_cloud_condensate
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [qcn]
    FieldName: qcn
    LongName: initial_mass_fraction_of_convective_cloud_condensate
    Units: kgkg-1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [cfcn]
    FieldName: cfcn
    LongName: convective_cloud_area_fraction
    Units: 1
    Tracer: true
    IOFile: tracer

  - FieldIONames: [frocean]
    FieldName: frocean
    LongName: fraction_of_ocean
    Units: 1
    Levels: 1
    IOFile: surface

  - FieldIONames: [frland]
    FieldName: frland
    LongName: fraction_of_land
    Units: 1
    Levels: 1
    IOFile: surface

  - FieldIONames: [frlandice]
    FieldName: frlandice
    LongName: fraction_of_landice
    Units: 1
    Levels: 1
    IOFile: surface

  - FieldIONames: [frlake]
    FieldName: frlake
    LongName: fraction_of_lake
    Units: 1
    Levels: 1
    IOFile: surface

  - FieldIONames: [frseaice]
    FieldName: frseaice
    LongName: fraction_of_ice
    Units: 1
    Levels: 1
    IOFile: surface

  - FieldIONames: [varflt]
    FieldName: varflt
    LongName: isotropic_variance_of_filtered_topography
    Units: m+2
    Levels: 1
    IOFile: surface

  - FieldIONames: [ustar]
    FieldName: ustar
    LongName: surface_velocity_scale
    Units: ms-1
    Levels: 1
    IOFile: surface

  - FieldIONames: [bstar]
    FieldName: bstar
    LongName: surface_bouyancy_scale
    Units: ms-2
    Levels: 1
    IOFile: surface

  - FieldIONames: [zpbl]
    FieldName: zpbl
    LongName: planetary_boundary_layer_height
    Units: m
    Levels: 1
    IOFile: surface

  - FieldIONames: [cm]
    FieldName: cm
    LongName: surface_exchange_coefficient_for_momentum
    Units: kgm-2s-1
    Levels: 1
    IOFile: surface

  - FieldIONames: [ct]
    FieldName: ct
    LongName: surface_exchange_coefficient_for_heat
    Units: kgm-2s-1
    Levels: 1
    IOFile: surface

  - FieldIONames: [cq]
    FieldName: cq
    LongName: surface_exchange_coefficient_for_moisture
    Units: kgm-2s-1
    Levels: 1
    IOFile: surface

  - FieldIONames: [kcbl]
    FieldName: kcbl
    LongName: KCBL_before_moist
    Units: none
    Levels: 1
    IOFile: surface

  - FieldIONames: [tsm]
    FieldName: tsm
    LongName: surface_temp_before_moist
    Units: K
    Levels: 1
    IOFile: surface

  - FieldIONames: [khl]
    FieldName: khl
    LongName: lower_index_where_Kh_greater_than_2
    Units: 1
    Levels: 1
    IOFile: surface

  - FieldIONames: [khu]
    FieldName: khu
    LongName: upper_index_where_Kh_greater_than_2
    Units: 1
    Levels: 1
    IOFile: surface

  - FieldIONames: [airdens, AIRDENS]
    FieldName: airdens
    LongName: moist_air_density
    Units: kgm-3
    IOFile: core